### ISSUE TITLE
simplify the definition of IDs in the menus

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#41]
We need to have active pages indicated as "active" in the CSS code, but the menu structure is getting messy with the ID numbers being moved around (see below). This needs to be simplified, either by not using id numbers, or by auto-generating the IDs based on other elements that will always be unique (e.g. the URL for each page).

```
- title: "Content"
  href: "/content"
  id: 8
  subitems:
    - title: "Bible"
      href: "/bible"
      id: 1
    - title: "Open Bible Stories"
      href: "/stories"
      id: 3

- title: "Tools"
  href: "/tools"
  id: 6
  subitems:
    - title: "Mobile Apps"
      href: "/apps"
      id: 2

- title: "Training"
  href: "/training"
  id: 7

- title: "Strategy"
  href: "/strategy"
  id: 9

- title: "About"
  href: "/about"
  id: 4
  subitems:
    - title: "Quality Assurance"
      href: "/quality"
      id: 4.1
    - title: "Statement of Faith"
      href: "/faith"
      id: 4.2
    - title: "Translation Guidelines"
      href: "/guidelines"
      id: 4.3
    - title: "Guiding Principles"
      href: "/principles"
      id: 4.4
    - title: "License &amp; Copyright"
      href: "/license"
      id: 4.5
    - title: "Contact"
      href: "/contact"
      id: 5
```
